import fs from 'fs';
import nbt from 'prismarine-nbt';

export interface BlockTask {
  x: number;
  y: number;
  z: number;
  blockName: string; // e.g. "minecraft:stone"
}

/**
 * Loads Sponge Schematic v2 (.schem) files.
 * Generated by WorldEdit, Litematica-export, or similar tools.
 */
export class SchematicLoader {
  async load(filePath: string, offsetX = 0, offsetY = 0, offsetZ = 0): Promise<BlockTask[]> {
    const buffer = fs.readFileSync(filePath);
    const { parsed } = await nbt.parse(buffer);

    const root = parsed.value as Record<string, nbt.NBT>;

    // Cast through unknown to satisfy strict NBT union types
    const r = root as unknown as Record<string, { value: unknown }>;

    const width  = r['Width'].value  as number;
    const height = r['Height'].value as number;
    const length = r['Length'].value as number;

    // Build reverse palette: index → blockName
    const paletteNbt = r['Palette'].value as Record<string, { value: number }>;
    const palette: Record<number, string> = {};
    for (const [name, entry] of Object.entries(paletteNbt)) {
      palette[entry.value] = name;
    }

    // BlockData is varint-encoded
    const rawBytes = r['BlockData'].value as Buffer | Int8Array | number[];
    const indices = decodeVarints(rawBytes);

    const tasks: BlockTask[] = [];

    for (let i = 0; i < indices.length; i++) {
      const blockName = palette[indices[i]];
      if (!blockName || blockName === 'minecraft:air') continue;

      // Sponge ordering: index = y * W * L + z * W + x
      const y = Math.floor(i / (width * length));
      const z = Math.floor((i % (width * length)) / width);
      const x = i % width;

      tasks.push({
        x: x + offsetX,
        y: y + offsetY,
        z: z + offsetZ,
        blockName,
      });
    }

    return tasks;
  }
}

function decodeVarints(bytes: Buffer | Int8Array | number[]): number[] {
  const result: number[] = [];
  let i = 0;

  while (i < bytes.length) {
    let value = 0;
    let shift = 0;
    let b: number;

    do {
      b = (bytes as number[])[i++] & 0xff;
      value |= (b & 0x7f) << shift;
      shift += 7;
    } while (b & 0x80);

    result.push(value);
  }

  return result;
}
